# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "dbf"
gem "sqlite3"
gem "rubyzip"
gem "lucky_case"
gem "ruby-progressbar"
